---
title: "20170205_김종은"
author: "20170205_김종은"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#3.5
x = c(28.5,48.3,40.2,34.8,50.1,44.0,27.2,37.8,27.2,46.1,31.3,50.1,31.3,24.8,42.2,23.0,30.1,36.5,40.2,46.1)
y = c(35.4,58.2,46.1,45.5,64.8,52.0,37.9,48.2,41.8,54.0,40.8,61.9,36.5,32.7,53.8,24.6,31.2,42.6,49.6,56.6)
```
```{r}
#a.산점도
plot(x,y)
```
```{r}
#b.상관계수
cor(x,y)
```
```{r}
#c.단순회귀모형
cam.lm = lm(y~x)
summary(cam.lm)
```
```{r}
#d
plot(x,y)+abline(cam.lm)
```
```{r}
#e
tb1 = abs((1.17696-0)/0.08718)
tb1
ptb1 = 2*pt(tb1, 18,lower.tail = FALSE)
ptb1
# cor.test(x=x,y=y) 했을 때의 pvalue와 동일
```
```{r}
#f
cor.test(x=x,y=y)
#95 percent confidence interval:
# 0.8851650 0.9819684

```
```{r}
#g
summary(cam.lm)
#R-squared:  0.9101
# 총 변동 중 회귀직선에 의해 설명되는 부분이 91.01%다.
```
```{r}
#h
res <- residuals(cam.lm)
res
deviance(cam.lm)
```


```{r}
#i

#install.packages("rio")
#install.packages("zip")
#install.packages("car")
library(car)
car::durbinWatsonTest(res)
#독립변수가 1개일 때 상한인 1.69보다 1.808528가 더 크므로 독립
```
```{r}
#j
plot(cam.lm)
#위 그래프에서는 가운데 선을 기준으로 각 점들이 잘 적합한 것으로 보임
```
```{r}
#k
predict(cam.lm, newdata = data.frame(x=50))
```

```{r}
#3.7
x = c(5.0,5.0,5.0,4.8,4.8,4.8,4.6,4.6,4.6,4.4,4.4,4.4,4.2,4.2,4.2,4.0,4.0,4.0)
y = c(2.51,2.57,2.43,2.62,2.74,2.68,2.83,2.91,2.98,3.17,3.05,3.09,3.32,3.22,3.29,3.44,3.52,3.55)

```
```{r}
#a.산점도
plot(x,y)
```
```{r}
#b.상관계수
cor(x,y)
```
```{r}
#c.단순회귀모형
lm = lm(y~x)
summary(lm)
```
```{r}
#d
plot(x,y)+abline(lm)
```
```{r}
#e
tb1 = abs((-0.99810-0)/0.03867)
tb1
ptb1 = 2*pt(tb1, 18,lower.tail = FALSE)
ptb1
# cor.test(x=x,y=y) 했을 때의 pvalue와 동일
```
```{r}
#f
cor.test(x=x,y=y)

#95 percent confidence interval:
# -0.9956970 -0.9678791

```
```{r}
#g
summary(lm)
#R-squared:  0.9765
# 총 변동 중 회귀직선에 의해 설명되는 부분이 97.65%다.
```
```{r}
#h
res <- residuals(lm)
res
deviance(lm)
```


```{r}
#i

#install.packages("rio")
#install.packages("zip")
#install.packages("car")
library(car)
car::durbinWatsonTest(res)
#독립변수가 1개일 때 상한인 1.69보다 1.925523가 더 크므로 독립
```
```{r}
#j
plot(lm)
#위 그래프에서는 가운데 선을 기준으로 각 점들이 위, 아래를 왔다갔다 하는 패턴을 보이고 있으므로 정규성에 살짝 어긋나 보입니다.
```
```{r}
#k
predict(lm, newdata = data.frame(x=5.5))
```


```{r}
#a.산점도
plot(x,y)
```
```{r}
#b.상관계수
cor(x,y)
```
```{r}
#c.단순회귀모형
cam.lm = lm(y~x)
summary(cam.lm)
```
```{r}
#d
plot(x,y)+abline(cam.lm)
```
```{r}
#e
tb1 = abs((1.17696-0)/0.08718)
tb1
ptb1 = 2*pt(tb1, 18,lower.tail = FALSE)
ptb1
# cor.test(x=x,y=y) 했을 때의 pvalue와 동일
```
```{r}
#f
cor.test(x=x,y=y)
#95 percent confidence interval:
# 0.8851650 0.9819684

```
```{r}
#g
summary(cam.lm)
#R-squared:  0.9101
# 총 변동 중 회귀직선에 의해 설명되는 부분이 91.01%다.
```
```{r}
#h
res <- residuals(cam.lm)
res
deviance(cam.lm)
```


```{r}
#i

#install.packages("rio")
#install.packages("zip")
#install.packages("car")
library(car)
car::durbinWatsonTest(res)
#독립변수가 1개일 때 상한인 1.69보다 1.808528가 더 크므로 독립
```
```{r}
#j
plot(cam.lm)
#위 그래프에서는 가운데 선을 기준으로 각 점들이 잘 적합한 것으로 보임
```
```{r}
#k
predict(cam.lm, newdata = data.frame(x=50))
```

```{r}
#3.14
x = c(1,1,1,1,2.5,2.5,2.5,2.5,4.8,4.8,4.8,4.8,5.0,5.0,5.0,5.0,6.5,6.5,6.5,6.5,7.8,7.8,7.8,7.8)
y = c(6,9,7,10,13,13,15,16,21,23,28,30,36,39,37,35,38,39,40,42,50,53,48,55)
```
```{r}
#a.산점도
plot(x,y)
```
```{r}
#b.상관계수
cor(x,y)
```
```{r}
#c.단순회귀모형
lm = lm(y~x)
summary(lm)
```
```{r}
#d
plot(x,y)+abline(lm)
```
```{r}
#e
tb1 = abs((6.4099-0)/0.3614)
tb1
ptb1 = 2*pt(tb1, 18,lower.tail = FALSE)
ptb1
# cor.test(x=x,y=y) 했을 때의 pvalue와 동일
```
```{r}
#f
cor.test(x=x,y=y)
#95 percent confidence interval:
# 0.9235439 0.9857360

```
```{r}
#g
anova(lm)
```
```{r}
lm2 = lm(y~ 0 + as.factor(x))
summary(lm2)
anova(lm,lm2)
F0 = 9.4788
pf(q=F0,df1=4,df2=18,lower.tail = FALSE)
#0.0002637002 이므로 유의수준 0.05에서 적합하다
```

