---
title: "20170205김종은"
author: "20170205_김종은"
date: "10/25/2020"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#4.1
y <- c(354,190,405,263,451,302,288,385,402,365,209,290,346,254,395,434,220,374,308,220,311,181,274,303,244)

x1 <- c(84,73,65,70,76,69,63,72,79,75,27,89,65,57,59,69,60,79,75,82,59,67,85,55,63)

x2 <- c(46,20,52,30,57,25,28,36,57,44,24,31,52,23,60,48,34,51,50,34,46,23,37,40,30)

```

```{r}
#a.산점도
plot(x1,y)
plot(x2,y)
```

```{r}
#b. 1차선형회귀모형 적합(x1)
lm.x1 <- lm(y~x1)
summary(lm.x1)

```
```{r}
#c. 1차선형회귀모형 적합(x2)
lm.x2 <- lm(y~x2)
summary(lm.x2)

```

```{r}
#d. 1차선형회귀모형 적합(x1,x2)
lm.x1x2 <- lm(y~x1+x2)
summary(lm.x1x2)

```

```{r}
#e. 유의성 검정
##F-statistic:  검정통계량 = 13.55
##p-값 : 1.443e-06    
##1.443e-06  < 0.05

##독립변수(몸무게, 나이)가 종속변수(콜레스테롤)에 미치는 영향에 대한 회귀모형은 통계적으로 유의하다.
```

```{r}
#f. 결정계수
##Multiple R-squared:  0.7056
##Adjusted R-squared:  0.6788 
##콜레스테롤(y)의 선형회귀모형은 몸무게(x1)와 나이(x2)에 의해 약 67.88%로 설명된다. 

```

```{r}
#g. 등분산성
par(mfrow=c(2,2))
plot(lm.x1x2)

##첫번째 x축에 모형적합값 y축에 잔차를 그린 plot에서 산점도가 중앙 선과 관계없이 분포된 것을 보아, 잔차의 등분산성을 만족한다. 
library(car)
ncvTest(lm.x1x2)


##ncvTest 결과 p = 0.83275 > .05인것을 보아, 모형 적합 값에 따라 오차의 분산이 변한다. 
##H0(귀무가설) : 독립변수에 상관없이 잔차의 분산이 동일하다 가 기각 안되고 채택됨.즉, 잔차의 등분산성을 만족한다. 

```

```{r}
#h
#Q-Q plot

qqPlot(lm.x1x2,simulate=TRUE,main="Q-Q_ plot")

##잔차의 probability plot을 본 결과, 점들은 비교적  45도 각도의 직선위에 있기 때문에 정규성이 있다. 

```

```{r}
# i. 잔차 정규분포 유의수준 5% 검정
library(nortest)
shapiro.test(lm.x1x2$residuals)

## p-value = 0.6588 > .05이므로 유의하지 않다. 즉, H0(귀무가설) : 모집단은 정규분포를 따른다.이 기각 안되고 채택됨. 즉, 잔차는 정규분포를 따른다. 
```

```{r}
#j
library(lmtest)
dwtest(lm.x1x2)

## p-value = 0.1791 > .05 이므로  잔차는 독립성을 따르지 않는다. 

```

```{r}
#k
predict(lm.x1x2, newdata = data.frame(x1=84,x2=54))
```


```{r}
#4.3
y <- c(82,89,101,107,115,122,127,137,147,166,174,175,177,184,187,189,194,197,201,204,255,328) #FFD

x1 <- c(1.468,1.605,2.168,2.054,2.467,1.294,2.183,2.426,2.607,4.567,4.588,3.618,5.855,2.898,3.88,0.455,8.088,6.502,6.081,7.105,8.548,6.321) #SPR

x2 <- c(3.3,3.664,4.87,4.72,4.11,3.75,3.97,4.65,3.84,4.92,3.82,4.32,4.53,4.48,5.39,4.99,4.5,5.2,5.65,5.4,4.2,6.45) #RGF

x3 <- c(0.166,0.154,0.177,0.275,0.298,0.15,0,0.117,0.155,0.138,0.249,0.143,0.172,0.178,0.101,0.008,0.251,0.366,0.106,0.089,0.222,0.187)  #PLF

x4 <- c(0.1,0.1,2.9,1.1,1,0.9,2.4,1.8,2.3,3.2,3.5,2.8,2.5,3,3,2.64,2.7,2.9,2.9,3.2,2.9,2) #SLF
  
x5 <- c(0,0,1,0,1,0,1,0,0,1,0,0,1,0,1,0,1,1,1,1,0,1) #CAR  

```

```{r}
#a.
y = log(y)
```

```{r}
#b.산점도
plot(x1,y)
plot(x2,y)
plot(x3,y)
plot(x4,y)
plot(x5,y)
```

```{r}
#c.다중회귀모형적합
lm.ffd = lm(y ~ x1+x2+x3+x4+x5) 
```


```{r}
#d. 유의성 검정
summary(lm.ffd)

##H0(귀무가설):회귀모형은 타당하지 않다. 즉, FFD는 기술수준변화와 관련 없다. 
##H1(대립가설):회귀모형은 타당하다. 즉, FFD는 기술수준변화와 관련 있다. 
##F-statistic:  검정통계량 =  15.41
##p-값 : 1.258e-05

## 독립변수(SPR,RGF,PLF,SLF,CAR)가 종속변수(FFD)에 미치는 영향에 대한 회귀모형은 통계적으로 유의하다.귀무가설 기각, 대립가설 채택, FFD는 기술수준변화와 관련 있다. 
```

```{r}
#e. 결정계수
##Multiple R-squared:  0.8281
##Adjusted R-squared:  0.7744


##FFD(y)의 선형회귀모형은 SPR(x1)과 RGF(x2)와 PLF(x3)와 SLF(x4)와 CAR(x5)에 의해 약 77.44%로 설명된다. 

```

```{r}
#f. 등분산성
par(mfrow=c(2,2))
plot(lm.ffd)

##첫번째 x축에 모형적합값 y축에 잔차를 그린 plot에서 산점도가 중앙 선과 관계없이 분포된 것을 보아, 잔차의 등분산성을 만족한다.  


library(car)
ncvTest(lm.ffd)

##ncvTest 결과 p = 0.89671> .05 인것을 보아,모형 적합 값에 따라 오차의 분산이 변한다. 
##H0(귀무가설) : 독립변수에 상관없이 잔차의 분산이 동일하다 가 기각 안되고 채택됨.즉, 잔차의 등분산성을 만족한다. 
```

```{r}
#g
#Q-Q plot

qqPlot(lm.ffd,simulate=TRUE,main="Q-Q_ plot")

##잔차의 probability plot을 본 결과, 점들은 비교적  45도 각도의 직선위에 있기 때문에 정규성이 있다. 

```


```{r}
#4.5
y <- c(44,25,10,28,25,72,45,25,12,24,46,8,15,28,26,27,4,14,21,22,60,10,60,12,28,39,14,8,11,7,23,16,26,8,11,12,50,9,13,22,23,31,20,65,9,12,21,13,10,4,18,10,7)

x1 <- c(2.8,3.1,2.59,3.36,2.8,3.35,2.99,2.99,2.92,3.23,3.37,2.72,3.47,2.7,3.24,2.65,3.41,2.58,2.81,2.8,3.62,2.74,3.27,3.78,2.9,3.7,3.4,2.63,2.65,3.26,3.15,2.6,2.74,2.72,3.11,2.79,2.9,2.74,2.7,3.08,2.18,2.88,3.04,3.32,2.8,3.29,3.56,2.74,3.06,2.54,2.78,2.81,3.26)

x2 <- c(6.1,5.1,6,6.9,7,5.6,6.3,7.2,6.9,6.5,6.8,6.6,8.4,5.9,6,6,7.6,6.2,6,6.4,6.8,8.4,6.7,8.3,5.6,7.3,7,6.9,5.8,7.2,6.5,6.3,6.8,5.9,6.8,6.7,6.7,5.5,6.9,6.3,6.1,5.8,6.8,7.3,5.9,6.8,8.8,7.1,6.9,6.7,7.2,5.2,6.6)

```

```{r}
#a.산점도
plot(x1,y)
plot(x2,y)
```

```{r}
#b. 다중선형회귀모형 적합(x1)
lm.x1x2 <- lm(y~x1+x2)
summary(lm.x1x2)

```



```{r}
#c. 유의성 검정

##H0(귀무가설):회귀모형은 타당하지 않다. 즉, 6개월 치료한 환자의 병적 측면의 정도는 생각방해 & 적대적인 의심과 관련 없다. 
##H1(대립가설):회귀모형은 타당하다. 즉, 6개월 치료한 환자의 병적 측면의 정도는 생각방해 & 적대적인 의심과 관련 있다. 
##F-statistic:  검정통계량 = 14.86 
##p-값 : 0.003815  
##0.003815  < 0.05

##독립변수(생각방해, 적대적인 의심)가 종속변수( 6개월 치료한 환자의 병적 측면의 정도)에 미치는 영향에 대한 회귀모형은 통계적으로 유의하다.
```

```{r}
#d. 결정계수
##Multiple R-squared:  0.1997
##Adjusted R-squared:  0.1677 
##6개월 치료한 환자의 병적 측면의 정도(y)의 선형회귀모형은 생각방해(x1)와 적대적인 의심(x2)에 의해 약 16.77%로 설명된다. 

```

```{r}
#e. 등분산성
#생각방해(x1)와 적대적인 의심(x2)을 독립변수(설명변수)로 갖는 모형의 결정계수
##Multiple R-squared:  0.1997
##Adjusted R-squared:  0.1677 

#생각방해(x1)를 독립변수(설명변수)로 갖는 모형의 결정계수
lm.m1 <- lm(y~x1) 
summary(lm.m1)
##Multiple R-squared:0.1114
##Adjusted R-squared:  0.09394 

#적대적인 의심(x2)을 독립변수(설명변수)로 갖는 모형의 결정계수
lm.m2 <- lm(y~x2)
summary(lm.m2)
##Multiple R-squared:  0.01145
##Adjusted R-squared:  -0.007938 

## 모형의 설명력을 뜻하는 각 회귀모형의 수정결정계수를 비교해봤을 때, 독립변수인 생각방해(x1)와 적대적인 의심(x2)이 모두 들어간 회귀모형의 수정결정계수가 0.1677로 가장 높다. 

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```




