---
title: "중간고사 Takehome exam"
author: "20170205_김종은"
date: "10/26/2020"
output: html_document
---
```{r}
# 1.

#(1) 공분산 
```
$$Cov(X,Y) = E(XY) - E(X)E(Y)$$
```{r}
# E(X) = m_x, E(Y) = m_y, E(XY) = m_xy
# Cov(X,Y) = E(XY) - E(X)*E(Y)
x = 488
y = 319
xy = 26184
m_x = x/6
m_y = y/6
m_xy = xy/6
cov = m_xy - (m_x * m_y)
cov
# 공분산이 양수이기 때문에, 두 변수가 같은 방향으로 변화한다. 즉, 몸무게가 증가하면 심장박동율도 증가한다(반대도 성립) 
```

```{r}
#(2) 상관계수
#E(X^2) = 40092, E(Y^2) = 17399이고,
m_x2 = 40092/6
m_y2 = 17399/6
```
$$Var(X) = E(x^2) - [E(X)]^2\\Var(Y) = E(Y^2) - [E(Y)]^2$$ 
```{r}
#이므로, Var(X) = E(X^2)-{E(X^2)}
v_x = m_x2 - (m_x^2)
# 마찬가지로, Var(Y) = E(Y^2)-{E(Y^2)}
v_y = m_y2 - (m_y^2)
#상관계수의 정의는 아래와 같으므로,
```
$$ \rho = \frac{Cov(X,Y)}{\sqrt{Var(X)Var(Y)}} $$ 
```{r}
corr = cov / sqrt(v_x*v_y)
corr
# 상관계수는 0.568708로 상관관계가 있다(어느정도 유의미하다)고 할 수 있다. 
```

```{r}
#(3)회귀식
sumx = 488
sumy = 319
sumx.2 = 40092
sumy.2 = 17399
sumxy = 26184

tXX <- matrix(c(6, sumx, sumx, sumx.2),nrow=2,byrow=T)
  
tXY <- matrix(c(sumy, sumxy),nrow=2)
beta <- solve(tXX)%*%tXY;beta

beta0 = 4.7990033
beta1 = 0.5946844

```
$$\hat{Y} =  4.7990033+ 0.5946844X_1 + e   $$


```{r}
#(4) 결정계수
# 결정계수  = 상관계수의 제곱 
rsq = corr^2
rsq
# rsq 값이 0.3234288이므로 학습된 단순 선형 회귀 모델은 몸무게(X)에 의해 약 32.34% 설명된다. (잘 설명하지 못한다.)
```


```{r}
#(5)MSE
sst=(6-1)*v_y
sse = (1-rsq)*sst;sse
mse = sse/(6-2);mse
#0.06562476
```
$$MSE = \frac{SSE}{n-2}\\
\frac{1}{n-2}\sum{(\hat{y}-y)^2}\\
SSE = (n-2)\sigma이므로\\$$

```{r}
#(6)
# 최소제곱 추정량 : SSR/(n-2)
ssr = sst-sse
ssr/(6-2)
# 최대가능도 추정량 : SSR/(n-2)
pie(2*v_y)^(-6/2)*exp(-t(sumy-(sumx*beta1))/sumy-(sumx*beta1))
```
$$모수 추정량:\\
\hat{\sigma^2} = \frac{RSS}{n-2}\\
SSR = S_{YY}-\hat{{\beta_1}^2}S_{XX}\\$$

```{r}
#(7) B1 95% 신뢰구간 
# t_0.025,4 = 0.741
beta1 - 0.741*sqrt((sse/(4))/v_x)
beta1 + 0.741*sqrt((sse/(4))/v_x)
# 8.517574와 8.540426 사이
```
$$b_1\pm t_{0.05/2,4} \sqrt{\frac{\sum{(y_i-\hat{y_i})^2/(n-2)}}{(x_i - \bar{x})^2}}$$

```{r}
#(8) 유의수준 a = 0.05에서 H0검정 
# H0 : B1= 0
t = beta1/sqrt(v_y);t
```

```{r}
#(9) X = 88일 때
# y = 4.799003 + 0.5946844x에 88을 넣으면,
X = 88
Y = 4.799003 + 0.5946844*X
Y 
# 57.13123이므로 신뢰구간 내 속함
```

```{r}
#(10) 
y95_s = m_x - 1.96*sqrt(v_x)/sqrt(6)
y95_b = m_x + 1.96*sqrt(v_x)/sqrt(6)

(y95_s < Y) & (Y< y95_b)
# 가 FALSE 이므로 신뢰할수없다.
```

```{r}
#(11)


```

```{r}
#2
X <- c(40,50,60,70,80,90,40,60,80,50)
Y <- c(69,175,272,335,490,415,72,265,492,180)
```


```{r}
#(1).산점도
plot(X,Y)  
cor(X,Y)
# 상관계수는 0.9568896로 농도와 채도는 강한 양적 선형관계를 갖는다.   
```
```{r}
#(2).단순회귀모형
light.lm = lm(Y~X)
summary(light.lm)
plot(X,Y) + abline(lm(Y~X))
```
$$\hat{Y}= -252.2971 + 8.5290X+e$$

```{r}
# (3) H0:B1=0   유의수준 5%검정
# p-value: 1.434e-05< 0.05 로 유의수준 5%에서 H0기각하며 추정된 회귀계수는 유의하다. 즉, 농도와 채도의 상관관계가 매우 유의하다. 

```

```{r}
#(4)
#Multiple R-squared:  0.9156
# 추정된 회귀직선의 설명력이 높은편이다.
#상관계수 0.9568896의 제곱이 R-squared:  0.9156로 동일하다.
```

```{r}
#(5) Yhat 추정

pred_y = predict(light.lm,newdata = data.frame(x=X))
pred_y

```

```{r}
#(6)
#독립성
library(lmtest)
dwtest(light.lm)
# durbinWatson결과,  p-value = 0.7575>0.05 이므로 H0채택, 잔차는 독립적이다. 

#등분산성
plot(light.lm, which = 1)
# x축에 모형적합값 y축에 잔차를 그린 plot에서 산점도가 fitted value가 500일 때를 제외하고 중앙 선과 관련있게 분포된 것을 보아, 대부분 잔차의 등분산 가정을 따른다.
```

```{r}
#(7)
##Q-Qplot
plot(light.lm, which = 2, pch=16)
## 정규 Q-Q Plot의 45도 선에 점들이 대체로 분포하며 정규성을 크게 벗어나지 않는다. 
library(nortest)
shapiro.test(light.lm$residuals)
## p-value = 0.1401 > .05이므로 유의하지 않다. 즉, 'H0(귀무가설) :정규분포를 따른다'가 채택됨. 즉, 잔차는 정규분포를 따른다. 
```

```{r}
#(8) X의 평균값 Y의 추정값, 신뢰구간
pred = predict(light.lm, newdata = data.frame(X=62), interval = "confidence")
pred
#추정값 : 276.5
# 신뢰구간: 241.4345 < Yhat < 311.5655 사이
```
```{r}
#(9)
pred2 = predict(light.lm, newdata = data.frame(X=c(45,55,65)), interval = "confidence")
pred2
# 45 일 때 추정값 : 131.5072
# 45 일 때 신뢰구간 : 81.33665 < Yhat < 181.6778
# 55 일 때 추정값 : 216.7971
# 55 일 때 신뢰구간 : 178.74604 < Yhat < 254.8482
# 65 일 때 추정값 : 302.0870
# 65 일 때 신뢰구간 : 266.45436 < Yhat < 337.7196
```

```{r}
#(10) 행렬
#추정계수
mat_x= as.matrix(X)
mat_y= as.matrix(Y)

x.2 = mat_x^2
y.2 = mat_y^2

tXX <- matrix(c(10,sum(mat_x),sum(mat_x),sum(x.2)),nrow=2,byrow=T)

  
tXY <- matrix(c(sum(mat_y),sum(mat_x*mat_y)),nrow=2)
beta <- solve(tXX)%*%tXY;beta
beta0 = -252.2971
beta1 = 8.5290
```


$$MSE = \frac{SSE}{n-2}\\
\frac{1}{n-2}\sum{(\hat{y}-y)^2}\\$$

```{r}

# MSE
yhat = beta0 + beta1*mat_x
sse = sum((mat_y-yhat)^2);sse
mse = sse/(10-2);mse
```

```{r}
# 결정계수
#R^2 = 1 - (SSE/SST)
sst=sum((mat_y-mean(mat_y))^2)
rsq = 1 - (sse/sst); rsq
```


```{r}
#3
library(readxl)
setwd("/Users/jongeun/Documents/Regression/")
df <- read_excel("SAT성적.xlsx")
#(1)
plot(df$X1,df$Y)
plot(df$X2,df$Y)
plot(df$X3,df$Y)

cor(df$X1,df$Y) # 상관계수는 0.5485531로 College GPA와 High school GPA는 다소 높은 양적 선형관계를 갖는다. 
cor(df$X2,df$Y) # 상관계수는 0.5905082로 College GPA와 SAT Total은 다소 높은 양적 선형관계를 갖는다.
cor(df$X3,df$Y) # 상관계수는 0.3514238로 College GPA와 Quality of letters of recommendation은 양적 선형관계가 있으나 낮다.
  
```

```{r}
#(2)
plot(df$X1+df$X2+df$X3,df$Y)
cor(df$X1+df$X2+df$X3,df$Y) # 상관계수는 0.5932331로 College GPA와 High school GPA, SAT Total, Quality of letters of recommendation은 다소 높은 양적 선형관계를 갖는다. 즉, High school GPA(X1), SAT Total(X2), Quality of letters of recommendation(X3) 변수가 증가하면 동시에 College GPA(Y)도 증가한다. (반대도 성립)

```

```{r}
#(3)
fit <- lm(Y~X1+X2+X3,data = df)
summary(fit)
```
$$\hat{Y}= -0.5920907 + 0.3599793X_1+ 0.0016918X_2+0.0323591X_3+e$$

```{r}
#(4) B1 = 0
# X1의 tvalue가 2.917, pvalue는 0.00464 < 0.05로 유의수준 5%에서 H0을 기각한다. 즉, 유의수준 5%에서 유의하다.

```

```{r}
#(5) B2 = 0
# X2의 tvalue가 4.869, pvalue는 5.95e-06 < 0.05로 유의수준 5%에서 H0을 기각한다. 즉, 유의수준 5%에서 유의하다.

```

```{r}
#(6) B3 = 0
# X3의 tvalue가 0.554, pvalue는 0.58121 > 0.05로 유의수준 5%에서 H0을 채택한다. 즉, 유의수준 5%에서 유의하지 않다.

```

```{r}
#(7)
#독립성
dwtest(Y~X1+X2+X3,data = na.omit(df))
# durbinWatson결과,  p-value =0.1838 >0.05 이므로 H0채택, 잔차는 독립적이다. 

#등분산성
plot(fit, which = 1)
# x축에 모형적합값 y축에 잔차를 그린 plot에서 중앙 선과 관련없이 비선형적으로 분포된 것을 보아, 잔차의 등분산성을 만족하지 않는다.

```

```{r}
#(9) 
##Q-Qplot
plot(fit, which = 2, pch=16)
## 정규 Q-Q Plot의 45도 선에 점들이 대체로 분포하며 정규성을 크게 벗어나지 않는다. (정규성이 있다.)
shapiro.test(fit$residuals)
## p-value = 0.445 > .05이므로 유의하지 않다. 즉, 'H0(귀무가설) :정규분포를 따른다'가 채택됨. 즉, 잔차는 정규분포를 따른다. 
```


```{r}
#(10)
# F 검정통계량 값이 가장 큰 변수부터 가장 큰 영향을 줌
fit_1 = lm(formula = Y ~ X1, data = df)
fit_2 = lm(formula = Y ~ X2, data = df)
fit_3 = lm(formula = Y ~ X3, data = df)

summary(fit_1)  #F-statistic: 33.57 
summary(fit_2)  #F-statistic: 41.76
summary(fit_3)  #-statistic: 10.99
# 따라서 X2(SAT Total)가 Y(College GPA)에 가장 큰 영향을 미친다. 
```
```{r}
#(11)
summary(fit)
# Multiple R-squared : 0.4673로, 학습된 다중 선형 회귀 모델은 High school GPA(X1)와 SAT Total(X2)과 Quality of letters of recommendation(X3)에 의해 약 46.73% 설명된다.
```

```{r}
#(12)
pred = predict(fit, newdata = data.frame(X1=3.0,X2=1200,X3=6), interval = "confidence")
pred
# 추정값 : 2.712109
#신뢰구간: 2.482267과 2.941951 사이
```


```{r}
#(13)
#추정계수
```
$$X'X = \begin{pmatrix}
n&\sum{X_1} \\
\sum{X_1}&\sum{X_1^2}\\
\end{pmatrix}\\
X'Y = \begin{pmatrix}
\sum{Y}\\
\sum{X_1Y}\\
\end{pmatrix}\\$$
```{r}
mat_x1= as.matrix(df$X1) 
mat_x2= as.matrix(df$X2) 
mat_x3= as.matrix(df$X3)
mat_y= as.matrix(df$Y) 
x1.2 = mat_x1^2
x2.2 = mat_x2^2
x3.2 = mat_x3^2

dim(df)

tXX <- matrix(c(80,sum(mat_x1),sum(mat_x2),sum(mat_x3),sum(mat_x1),sum(x1.2),sum(mat_x1*mat_x2),sum(mat_x1*mat_x3),sum(mat_x2),sum(mat_x1*mat_x2),sum(x2.2),sum(mat_x2*mat_x3),sum(mat_x3),sum(mat_x1*mat_x3),sum(mat_x2*mat_x3),sum(x3.2)),nrow=4,byrow=T)

  
tXY <- matrix(c(sum(mat_y),sum(mat_x1*mat_y),sum(mat_x2*mat_y),sum(mat_x3*mat_y)),nrow=4)

beta <- solve(tXX)%*%tXY
beta
beta0 = -0.592090738 
beta1 = 0.359979270  
beta2 =  0.001691756 
beta3 = 0.032359058    

```


$$MSE = \frac{SSE}{n-2}\\
\frac{1}{n-2}\sum{(\hat{y}-y)^2}\\$$

```{r}

# MSE
yhat = beta0 + beta1*mat_x1 + beta2*mat_x2 + beta3*mat_x3
sse = sum((mat_y-yhat)^2);sse
mse = sse/(80-2)
mse
```

```{r}
# 결정계수
#R^2 = 1 - (SSE/SST)
sst=sum((mat_y - mean(mat_y))^2)
rsq = 1 - (sse/sst); rsq
```

